# fly.toml app configuration file generated for cynical-myopia on 2025-06-24T04:00:31+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cynical-myopia'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8050
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
